#!/bin/sh
# postinst script for pixelserv-tls
#

set -e

case "$1" in

	configure)
	  CERTPATH=/var/cache/pixelserv
	  mkdir -p $CERTPATH
	  chown nobody:nogroup $CERTPATH

	  update-rc.d pixelserv-tls defaults
	  invoke-rc.d pixelserv-tls start
	  cat <<EOF
--------------------------------------------------------------------
Remember to copy "ca.crt" and "ca.key" into $CERTPATH and then run:
  service pixelserv-tls restart

To generate "ca.crt" and "ca.key," follow this guide:
  https://github.com/kvic-z/pixelserv-tls/wiki/Create-and-Import-the-CA-Certificate

pixelserv-tls binds to all interfaces by default. Specify an IPv4 or
an interface as argument in "/etc/default/pixelserv" to override this.

pixelserv-tls requires port 80 and 443 or it fails to start.
On EdgeOS, you may want to move GUI to 8080 and 8081 instead.
Run the following Vyatta CLI:
  configure
  set service gui http-port 8080
  set service gui https-port 8081
  commit; save; exit
--------------------------------------------------------------------
EOF
	;;
	abort-upgrade|abort-remove|abort-deconfigure)
	  exit 0
	;;

	*)
	  echo "postinst called with unknown argument \`$1'" >&2
	  exit 1
	;;

esac

exit 0
